### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by tapanacharya** [AhmedMah/ClinicManagement#3]
While running the "enable-migration" command visual studio 2017 not responding and  I have to close forcefully. As soon as I hit the command, its showing not responding.

After that, if I run the "add-migration "InitialDb" command, its giving me below error:

![Capture](https://user-images.githubusercontent.com/36747477/55474675-c3a5c600-55df-11e9-88b0-185b9b95a64d.JPG)

Please help me to resolve the issues.

Thank you

**Comment by TheHokieCoder** [comment]
@tapanacharya I was able to get the migrations working by doing this:

1. Enable migrations, which once run, confirms that migrations are already enabled.
2. Run `Update-Database` _before_ running the `Add-Migration "InitialDb"` command. This will cause EF to catch up on all of those migrations listed in your error screenshot. However, it will fail on the migration `201805051343194_RemoveStringLengthFromMedicine` due to the default value constraint on the `Medicine` column.
3. Manually connect to the database using Server Explorer and modify the `Prescriptions` table, removing the default value for the `Medicine` column. 
4. Run `Update-Database` again. The migrations should fast-forward all the way to the most recent with a few warnings, but no errors.
5. Now run `Add-Migration "InitialDb"`. Then run `Update-Database` again.
At this point it seemed the database was properly set up and working within the app, but I have not tested all areas/functions to be sure of this.

**Comment by AhmedMah** [comment]
Deleting migrations folder and then running enable -migrations; add-migration InitialDb;  update-database. Will solve this issue.

**Comment by tapanacharya** [comment]
yes I tried the same way and it worked...
Thank you so much for your help..

**Comment by TheHokieCoder** [comment]
@AhmedMah If you are OK with your solution, basically that all of the current DB migrations in your project are "development" migrations and not needed by us end users, can you remove them from the project so that newcomers don't run into the same issue?

Alternatively I think you would need to fix the migrations so that the history isn't broken at migration `201805051343194_RemoveStringLengthFromMedicine`, allowing newcomers to replay your migrations. And this would also require that you update your instructions in the readme since it wouldn't be necessary to enable migrations nor create an "InitialDb" migration.

**Comment by AhmedMah** [comment]
@TheHokieCoder  I removed development migrations. Thanks
